version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${NEST_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${NEST_MYSQL_DATABASE}
      MYSQL_USER: ${NEST_MYSQL_USER}
      MYSQL_PASSWORD: ${NEST_MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      NEST_MYSQL_HOST: localhost
      NEST_MYSQL_PORT: ${NEST_MYSQL_PORT}
      NEST_MYSQL_USER: ${NEST_MYSQL_USER}
      NEST_MYSQL_PASSWORD: ${NEST_MYSQL_PASSWORD}
      NEST_MYSQL_DATABASE: ${NEST_MYSQL_DATABASE}
      NEST_MYSQL_CHARSET: ${NEST_MYSQL_CHARSET}
      NEST_MYSQL_TIMEZONE: ${NEST_MYSQL_TIMEZONE}
      NEST_ENCRYPTION_KEY: ${NEST_ENCRYPTION_KEY}
      NEST_ENCRYPTION_IV: ${NEST_ENCRYPTION_IV}

volumes:
  mysql_data:
