version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "3000:3000"
    networks:
      - nest_network
    env_file:
      - .env

networks:
  nest_network:
    driver: bridge
