version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "3000:3000"
    networks:
      - nest_network
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: coderzzx
    ports:
      - "3306:3306"
    networks:
      - nest_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  nest_network:
    driver: bridge

volumes:
  mysql_data:
